### ISSUE TITLE
HackErrorSuppressor doesn't suppress in HHVM 3.19.1

### ISSUE THREAD

**Issue by acrylic-origami** [fredemmott/hack-error-suppressor#1]
It seems that somewhere between HHVM 3.18.3 and 3.19.1, the backtrace for a Hack typechecker error changed. The first entry in the backtrace passed to the custom error handler no longer always points to a function call, so the `function` field isn't always set.

With a minimal project setup:

```
hh_autoload.json:
{ "roots": ["src/"] }

composer.json:
{
	"require": {
		"facebook/hhvm-autoload": "dev-master"
	}
}
```

In 3.19.1, the first entry of the backtrace is:

```
array(2) {
  ["file"]=>
  string(88) "/path/to/project/root/vendor/facebook/definition-finder/autoload_files.php"
  ["line"]=>
  int(21)
}
```

In contrast to 3.18.3:

```
array(4) {
  ["file"]=>
  string(88) "/path/to/project/root/vendor/facebook/definition-finder/autoload_files.php"
  ["line"]=>
  int(21)
  ["function"]=>
  string(29) "HH\Client\typecheck_and_error"
  ["args"]=>
  array(0) {
  }
}
```

Without the `function` field set, the error handler lets the "Error: could not find a .hhconfig file..." error pass through it.

**Comment by fredemmott** [comment]
Thanks, I'll look this evening (and change the travis setup to something docker-based that actually supports 3.19 :( )

**Comment by fredemmott** [comment]
Well this'll be fun... there's tests that are supposed to cover this, appear to be working, and are passing :/

True minimal repro:

```
cd $(mktemp -d)
hhvm -d hhvm.jit=0 /usr/local/bin/composer require facebook/hhvm-autoload
```

**Comment by fredemmott** [comment]
Full trace from composer -vvv:

```
Exception trace:
 () at /tmp/hhtest/vendor/facebook/definition-finder/autoload_files.php:21
 Composer\Util\ErrorHandler::handle() at /tmp/hhtest/vendor/fredemmott/hack-error-suppressor/src/HackErrorSuppressor.php:62
 FredEmmott\HackErrorSuppressor->callOldHandler() at /tmp/hhtest/vendor/fredemmott/hack-error-suppressor/src/HackErrorSuppressor.php:76
 FredEmmott\HackErrorSuppressor->handleError() at /tmp/hhtest/vendor/fredemmott/hack-error-suppressor/src/HackErrorSuppressor.php:37
 Closure$FredEmmott\HackErrorSuppressor::enable() at n/a:n/a
 trigger_error() at n/a:n/a
 HH\Client\TypecheckResult->triggerError() at n/a:n/a
 HH\Client\typecheck_and_error() at /tmp/hhtest/vendor/facebook/definition-finder/autoload_files.php:21
 include() at /tmp/hhtest/vendor/composer/autoload_real.php:66
```

**Comment by fredemmott** [comment]
This is hidden from the unit test because of another bug: https://github.com/fredemmott/hack-error-suppressor/blob/master/src/HackErrorSuppressor.php#L37 - missing return, I'm too used to short lambadas :/
